### ISSUE TITLE
Error: unable to fetch collection

### ISSUE THREAD

**Issue by jareem** [pynt-io/pynt#10]
Hi,

During the run I receive this error whatever the collection I am trying to scan (even goat).
I cannot find the reason why.
I already checked the API, collection variable etc.

Any idea?

Thanks.

**Comment by amosovercast** [comment]
Hey @jareem , couled you please provide more detailes about the scan such as scan id, user name you are logged in with? also I would love if you join our slack community so we could debug this faster: https://www.pynt.io/community
