### ISSUE TITLE
Unable to Sign Up on browsers like Microsoft Edge and Brave

### ISSUE THREAD

**Issue by Ayushparui** [pynt-io/pynt#13]
While I was trying to sign up using Edge, the webpage didn't respond with anything it was stuck on the same page.

**Comment by amosovercast** [comment]
Hey @Ayushparui  please verify no AdBlocker in place. Also feel free to join our community: https://join.slack.com/t/pynt-community/shared_invite/zt-1mvacojz5-WNjbH4HN8iksmKpCLTxOiQ
