### ISSUE TITLE
We encountered SSL issues and could not proceed, this may be the cause of a VPN or a Firewall in place.

### ISSUE THREAD

**Issue by AvinashReddy-Git** [pynt-io/pynt#14]
pynt
API Security testing autopilot
Pynt CLI version 0.1.42

We encountered SSL issues and could not proceed, this may be the cause of a VPN or a Firewall in place.
avinash.reddy@C02F73G5ML85 ~ % pynt --debug
API Security testing autopilot
Pynt CLI version 0.1.42

We encountered SSL issues and could not proceed, this may be the cause of a VPN or a Firewall in place.

**Comment by orelazar1** [comment]
Hey @AvinashReddy-Git. This issue occurs since you have some vpn/firewall that our cli does not trust it's CA. We are aware of it and working on a fix. Until fix is deployed you can turn off the VPN/Firewall if possible.

**Comment by mattvaldes** [comment]
Why not leave this open until it is fixed? It seems like this would be a common problem.
