### ISSUE TITLE
Collection is empty

### ISSUE THREAD

**Issue by nightmare-wolf** [pynt-io/pynt#16]
![image](https://github.com/pynt-io/pynt/assets/41340083/a0b7b2dc-5f59-4fcc-bd04-f2110b51fbf9)

After setting everything up, my pynt in postman has an empty collection.
Where the documentation shows I should have a collection to use to test against my API environment:
![image](https://github.com/pynt-io/pynt/assets/41340083/36633cc8-cbbf-41fc-a244-bb0dd9928c07)

How do i get a copy of this collection to import into my pynt in postman?

**Comment by amosovercast** [comment]
Hey @Cy-Beard , this looks like the old Pynt collection. Please fork again using this [link](https://www.postman.com/pynt-io/workspace/pynt/overview). Also feel free to join our Slack community: https://join.slack.com/t/pynt-community/shared_invite/zt-1mvacojz5-WNjbH4HN8iksmKpCLTxOiQ . The community is alive and helps a lot with setup and use cases issues :)
