### ISSUE TITLE
Wrong file name in the docs

### ISSUE THREAD

**Issue by palmerabollo** [pynt-io/pynt#17]
Hi.

There is a minor issue in the doc > Getting Started > Pynt Command. The doc at https://docs.pynt.io/documentation/onboarding/getting-started/pynt-command references a goat_functional_test**er**.py file.

The link is fine but the file name is goat_functional_test.py (no "er" suffix) at https://github.com/pynt-io/pynt/tree/main/goat_functional_tests.

Thanks.

**Comment by origold1** [comment]
Fixed. thanks @palmerabollo !
