### ISSUE TITLE
Error: The server encountered internal error and could not proceed

### ISSUE THREAD

**Issue by ganesh2183** [pynt-io/pynt#4]
Hi,

I'm trying to run Pynt in postman desktop behind corporate proxy. I have tried adding proxy in docker config file as well in postman settings. But still i'm getting error in postman as "The server encountered internal error and could not proceed, please run again".

Same i tried in my personal laptop, it is working as expected, but not working in my office network.

Kindly help me to resolve this issue.

**Comment by amosovercast** [comment]
Hi Ganesh,
First of all - thank you very much for the feedback and support in our mission securing API for all developers and testers!
The issue with proxy is a known issue for us and will be resolved in future versions.
for the moment we can suggest the following based on our past experience:
* Try to validate docker network is actually being routed via the proxy, previously we've experienced (when client used OpenVPN) docker network was not routed via the proxy.
** A simple check would be to spin up vanilla alpine docker and trying to reach the assets behind the proxy and validate the issue. 
* Can you try to remove proxy and run again?
* If the proxy is performing TLS termination this is a moderate issue the will be solved shortly by us. I can suggest removing the TLS termination option (if possible).
If the issue persists we can jump on a quick call and try to resolve the issue online.
Thank you very much.

**Comment by ganesh2183** [comment]
> Hi Ganesh, First of all - thank you very much for the feedback and support in our mission securing API for all developers and testers! The issue with proxy is a known issue for us and will be resolved in future versions. for the moment we can suggest the following based on our past experience:
> 
> * Try to validate docker network is actually being routed via the proxy, previously we've experienced (when client used OpenVPN) docker network was not routed via the proxy.
>   ** A simple check would be to spin up vanilla alpine docker and trying to reach the assets behind the proxy and validate the issue.
> * Can you try to remove proxy and run again?
> * If the proxy is performing TLS termination this is a moderate issue the will be solved shortly by us. I can suggest removing the TLS termination option (if possible).
>   If the issue persists we can jump on a quick call and try to resolve the issue online.
>   Thank you very much.

I tried with / without proxy, but still same issue. How to perform TLS termination ?
Can we have quick call to fix this issue ?

**Comment by amosovercast** [comment]
Hey Ganesh, we were on our weekend. Can you please send an email to `support@pynt.io` and we will be sure to return an email with further details about how to schedule a call with us. Thanks!

**Comment by ganesh2183** [comment]
@amosovercast I have sent mail, could you please reply. Help me to resolve this issue.

**Comment by ganesh2183** [comment]
Hi @amosovercast, Any update on this issue ?

**Comment by oferhakimi** [comment]
Hi Ganesh,

Not yet, we will update.

BR,
Ofer.
