### ISSUE TITLE
[Question] : Please explain the Test status - Not executed & Not supported

### ISSUE THREAD

**Issue by rakeshkmr516** [pynt-io/pynt#8]
@origold1  @oferhakimi - Please explain the Test status - Not executed & Not supported - Do we need to do any additional configuration to make the not executed checks

**Comment by origold1** [comment]
Hi @rakeshkmr516 , thank you for posting the question.
We agree that our Security Summary table is a bit misleading now, we are working on an overhaul of the report structure.
But for now, "Not executed" is relevant to API1 and API5 - adding more then one user to the functional tests will enable Pynt to test these as well. "Not supported" means we dont have tests for this category yet (API9).
We will update when the new report is ready.

Thank you for running Pynt !
Ori

**Comment by rakeshkmr516** [comment]
Hi @origold1 
Appreciate your quick response. 

1. Not executed - Adding more than one user to functional tests - Does it mean adding more than one iterations value in postman or any specific pynt configuration 

2. Tests & Not supported - Looking forward to tests for the category API9 & updated changes report

**Comment by origold1** [comment]
Hi @rakeshkmr516 
Adding more users means having a second user in your functional test collection. 
Look at the goat collection example:
https://www.postman.com/pynt-io/workspace/pynt/collection/22821296-23bb40ff-e0a6-40eb-8bf1-13016c206f8b?ctx=documentation
We have 2 users (James and Lars) performing login, get account and get transatctions requests.
Note that the second user does not have to do exactly all requests as the first user, login and a few requests are enough.

Ori
