### ISSUE TITLE
[Feature Request]-Add some more components/factors to the report

### ISSUE THREAD

**Issue by sseenivasan89** [pynt-io/pynt#9]
Add a few other factors also to the report like the below status and add some color tags to make the report user friendly
if possible have the report in HTML format to share with others

- Critical
- Minor
- Major

![image](https://user-images.githubusercontent.com/44080743/206406887-61dae8d5-e525-4ec2-b02a-2fcd2c011c10.png)

**Comment by amosovercast** [comment]
Hey @sseenivasan89 ,

Pynt is out with a new report version. Check out the new docker and new collection. You would be pleased to find the report got a complete redesign and in an html format which you can save and share with folks. 

Waiting to hear from you :)
